name: Code reviews

on:
  push:
    branches-ignore:
      - 'main'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: .
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Format:
    name: 'Format check'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt
        working-directory: ${{ env.WORKING_DIR }}
        
  Validate:
    needs: Format
    name: 'Validate check'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}          

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
        
  Tfsec:
    needs: Validate
    name: 'Tfsec security check'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ env.WORKING_DIR }}
          github_token: ${{ env.GITHUB_TOKEN }}
          args: --minimum-severity HIGH
